// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ6IlMqLidoV8dzprFtRPJt4wfXW1k7Y8',
    appId: '1:814761519101:web:8f645ef7a1dc03528f9b94',
    messagingSenderId: '814761519101',
    projectId: 'choreo-flutter',
    authDomain: 'choreo-flutter.firebaseapp.com',
    storageBucket: 'choreo-flutter.firebasestorage.app',
    measurementId: 'G-2FMMS5EK04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxqDxdG5uaw2eoRwVN-1lzPY651ukmxhk',
    appId: '1:814761519101:android:e4ff622695ebbe878f9b94',
    messagingSenderId: '814761519101',
    projectId: 'choreo-flutter',
    storageBucket: 'choreo-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0NQfsS-w_vxHWTsN88ib74BQkS2HsOCY',
    appId: '1:814761519101:ios:92f998eecc8927288f9b94',
    messagingSenderId: '814761519101',
    projectId: 'choreo-flutter',
    storageBucket: 'choreo-flutter.firebasestorage.app',
    iosBundleId: 'com.example.appp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0NQfsS-w_vxHWTsN88ib74BQkS2HsOCY',
    appId: '1:814761519101:ios:92f998eecc8927288f9b94',
    messagingSenderId: '814761519101',
    projectId: 'choreo-flutter',
    storageBucket: 'choreo-flutter.firebasestorage.app',
    iosBundleId: 'com.example.appp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ6IlMqLidoV8dzprFtRPJt4wfXW1k7Y8',
    appId: '1:814761519101:web:4b205f3f283a66b78f9b94',
    messagingSenderId: '814761519101',
    projectId: 'choreo-flutter',
    authDomain: 'choreo-flutter.firebaseapp.com',
    storageBucket: 'choreo-flutter.firebasestorage.app',
    measurementId: 'G-5DNWP1CQKL',
  );
}
